version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    labels:
      - dependencies
    groups:
      artifacts:
        patterns: [actions/*-artifact, actions/deploy-pages]
      runtimes:
        patterns: [oven-sh/setup-bun, shivammathur/setup-php]

  - package-ecosystem: composer
    directories:
      - /
      - /packages/*
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      linting:
        patterns:
          - dealerdirect/phpcodesniffer-composer-installer
          - phpcompatibility/*
          - squizlabs/php_codesniffer
      testing:
        patterns:
          - brain/monkey
          - mockery/mockery
          - phpunit/*
          - sebastian/*
      wp-cli:
        patterns: ['wp-cli/*']
    labels:
      - dependencies

  - package-ecosystem: bun
    directories:
      - /
      - /packages/*
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '@types/bun'
      - dependency-name: '@types/node'
      - dependency-name: 'typescript'
    groups:
      commitlint:
        patterns: ['@commitlint/*']
    labels:
      - dependencies
