x-packages: &packages
  - ./packages/blank-option:/var/www/html/wp-content/plugins/blank-option
  - ./packages/custom-theme:/var/www/html/wp-content/themes/custom-theme

services:
  web:
    extends:
      file: docker/compose.base.yml
      service: web
    ports:
      - ${FORWARD_WEB_PORT:-8080}:80
    volumes: *packages

  cli:
    extends:
      file: docker/compose.base.yml
      service: cli
    volumes: *packages

  db:
    extends:
      file: docker/compose.base.yml
      service: db
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306

  mail:
    extends:
      file: docker/compose.base.yml
      service: mail
    ports:
      - ${FORWARD_MAILPIT_PORT:-8025}:8025

networks:
  default:
     name: wp-env
