name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    uses: projek-xyz/actions/.github/workflows/configure.yml@main
    secrets: inherit
    with:
      php-version: 8.1

    permissions:
      pull-requests: write
      contents: read

  tests:
    name: with WP ${{ matrix.wp }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    needs: [prepare]
    outputs:
      should-upload: ${{ steps.dist-archive.outputs.should-upload }}

    env:
      DB_NAME: ${{ github.repository_owner }}
      DB_USER: ${{ github.repository_owner }}
      DB_PASS: secret
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wp }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1']
        wp: ['6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION || '1.3.10' }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: xdebug
          tools: composer, wp

      - name: Retrieve cache dirs
        id: caches
        run: |
          echo "composer-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          echo "wpcli-dir=$(wp cli info --format=json | jq -r '.wp_cli_cache_dir_path')" >> $GITHUB_OUTPUT

      - name: Set up Composer cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.caches.outputs.composer-dir }}
          key: composer-php${{ env.PHP_VERSION }}-wp${{ env.WP_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-php${{ env.PHP_VERSION }}-wp${{ env.WP_VERSION }}-

      - name: Set up WP-CLI cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.caches.outputs.wpcli-dir }}
          key: wpcli-php${{ env.PHP_VERSION }}-wp${{ env.WP_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: wpcli-php${{ env.PHP_VERSION }}-wp${{ env.WP_VERSION }}-

      - name: Install dependencies
        run: |
          composer update --ansi --no-interaction --no-progress --prefer-dist

      - name: Set up WordPress
        shell: bash
        env:
          DB_HOST: 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
          SITE_PLUGINS: blocksy-companion
          SITE_THEMES: blocksy
        run: |
          scripts/init-wp.sh

      # - name: Lint
      #   run: |
      #     vendor/bin/phpcs

      - name: Unit Test
        run: |
          composer test --ansi
